
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[197] =
    {   0,
        0,    0,   83,   81,    1,    2,   81,   81,   81,    3,
       56,   65,   81,   70,   71,   54,   52,   76,   53,   78,
       55,   29,   29,   77,   79,   61,   50,   62,   80,   23,
       23,   23,   23,   72,   73,   67,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   74,
       66,   75,   68,    1,    2,    2,   60,    0,   37,   35,
        0,    3,   44,   45,    0,   38,   36,    0,   41,   39,
       40,   69,   30,   51,   42,   30,    0,   24,   24,   24,
       24,   24,   29,   63,   57,   59,   58,   64,   23,    0,
        0,   23,   23,   23,   47,   23,   23,   23,   23,   23,

       23,    5,   10,   18,   23,   16,   23,   23,   23,   23,
       46,    2,   35,    0,   36,    0,    0,   43,   24,   26,
       24,   24,   28,   28,   24,   24,   27,   24,   24,   25,
       24,   24,   48,   49,    0,   33,    0,    0,   34,    0,
       23,   23,   23,   15,   23,   23,    4,   23,   23,    8,
       17,   23,   23,    0,   23,    0,    0,    0,    0,    0,
        0,   28,   30,   30,   23,   21,   19,   23,   23,    6,
        7,   14,   23,   22,   23,    0,    0,    0,   20,   11,
       23,   23,   22,    9,   31,   32,    0,    0,   23,   13,
        0,   23,    0,   12,   32,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,    1,   28,   29,   30,   29,   29,   31,   32,
       33,   33,   33,   33,   33,   33,   33,   34,   35,   33,
       33,   33,   33,   36,   33,   33,   33,   37,   33,   33,
       38,   39,   40,   41,   33,    1,   42,   43,   44,   45,

       46,   47,   33,   48,   49,   33,   50,   51,   33,   52,
       53,   54,   33,   55,   56,   57,   58,   33,   59,   37,
       33,   33,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    4,    4,
        4,    4,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[211] =
    {   0,
        0,    0,  584,  585,  581,  580,  578,  554,   61,    0,
      553,  552,   62,  585,  585,  551,  550,  585,   42,   54,
       52,   85,   62,  585,  585,   60,  549,   61,  585,    0,
       84,  521,  518,  585,  585,  546,  519,  515,  516,  522,
      516,   86,   62,  513,  510,  522,  517,  511,  513,  585,
      534,  585,  585,  557,  556,  555,  585,   74,  585,  550,
      552,    0,  585,  585,   88,  585,  544,  550,  585,  585,
      585,  585,  113,  526,  585,  121,  126,    0,  167,  230,
      293,  356,    0,  525,  585,  585,  585,  524,    0,   60,
       85,  498,  471,  460,  585,  456,  447,  440,  444,   54,

      435,    0,    0,    0,  432,    0,  432,  430,  469,  436,
      585,  482,  585,   91,  585,  111,  135,  585,    0,  585,
       92,    0,  585,  141,  401,    0,  585,  145,    0,  585,
      405,    0,  585,  585,  119,  585,    0,  418,  585,    0,
      427,  436,  435,    0,  438,  422,    0,  431,  431,    0,
        0,  420,  416,    0,  422,  423,  466,  468,  420,  460,
      126,  419,  423,  434,  423,    0,    0,  418,  418,    0,
        0,    0,  411,    0,  418,  457,  423,  421,    0,    0,
      101,   85,    0,    0,  585,  585,  422,  455,   65,    0,
      436,   73,  107,    0,   79,  585,  494,  499,  504,  507,

      509,  511,  516,  521,  526,  531,  536,   66,  538,  543
    } ;

static const flex_int16_t yy_def[211] =
    {   0,
      196,    1,  196,  196,  196,  196,  196,  196,  197,  198,
      196,  196,  199,  196,  196,  196,  196,  196,  196,  196,
      196,  200,  200,  196,  196,  196,  196,  196,  196,  201,
      201,  201,  201,  196,  196,  196,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  196,
      196,  196,  196,  196,  196,  196,  196,  197,  196,  196,
      197,  198,  196,  196,  199,  196,  196,  199,  196,  196,
      196,  196,  196,  196,  196,  196,   23,  202,  196,  196,
      196,  196,   23,  196,  196,  196,  196,  196,  201,  203,
      204,  201,  201,  201,  196,  201,  201,  201,  201,  201,

      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      196,  196,  196,  205,  196,  206,  207,  196,  202,  196,
      202,  202,  196,  207,  202,  202,  196,  202,  202,  196,
      202,  202,  196,  196,  203,  196,  203,  204,  196,  204,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  208,  201,  205,  205,  205,  206,  196,
      206,  207,  196,  196,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  209,  201,  205,  206,  210,  201,  201,
      201,  201,  209,  201,  196,  196,  206,  210,  201,  201,
      210,  201,  206,  201,  206,    0,  196,  196,  196,  196,

      196,  196,  196,  196,  196,  196,  196,  196,  196,  196
    } ;

static const flex_int16_t yy_nxt[649] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   24,   25,   26,   27,   28,   29,   30,   30,
       30,   31,   30,   32,   30,   33,   30,   34,    4,   35,
       36,   37,   38,   39,   40,   41,   42,   30,   43,   30,
       30,   44,   45,   46,   47,   30,   48,   30,   49,   50,
       51,   52,   53,   59,   66,  136,   60,   71,   72,   74,
      174,   67,   73,   73,   73,   73,   59,   75,   76,  113,
       83,   83,   83,   83,   84,   85,   87,   88,  186,   90,
       66,   90,   80,   91,  139,   91,  157,  115,  137,   61,

       68,   76,  148,   77,   77,   77,   77,   80,  102,  149,
      121,  121,   61,  103,   79,   80,  195,  104,  194,   81,
      160,   82,  192,  140,  136,   92,   68,   79,  196,  158,
       80,   73,   73,   73,   73,  178,  190,   81,  101,   73,
       73,   73,   73,  117,   77,   77,   77,   77,  162,  161,
      162,  117,  189,  163,  163,  163,  163,  137,  117,  164,
      164,  164,  164,  128,  128,  128,  117,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  121,  121,  122,  122,  120,
      120,  120,  120,  120,  120,  122,  122,  122,  122,  122,

      122,  122,  122,  122,  120,  120,  120,  120,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  120,  120,  120,  120,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  124,  123,  124,  123,  123,  125,  125,
      125,  125,  123,  123,  123,  123,  123,  123,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  123,  123,  123,
      123,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  123,
      123,  123,  123,  127,  127,  127,  127,  127,  127,  127,

      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  128,  128,  128,  129,  127,  127,  127,  127,  127,
      127,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      127,  127,  127,  127,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  127,  127,  127,  127,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  131,  131,  131,  131,  130,  130,
      130,  130,  130,  130,  131,  131,  131,  131,  132,  132,
      132,  132,  132,  130,  130,  130,  130,  131,  131,  131,

      131,  131,  131,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  130,  130,  130,  130,  125,
      125,  125,  125,  131,  131,  131,  131,  139,  157,  160,
      160,  160,  186,  131,  131,  131,  131,  163,  163,  163,
      163,  163,  163,  163,  163,  193,  131,  131,  131,  131,
      131,  131,  164,  164,  164,  164,  140,  159,  161,  188,
      161,  158,  185,  184,  191,  182,  181,  180,  179,  177,
      196,  176,  175,  173,  188,  172,  171,  170,  169,  168,
      167,  166,  165,  112,  155,  154,  153,  152,  151,  150,
      147,  146,  145,  188,   58,   58,   58,   58,   58,   62,

      144,   62,   62,   62,   65,   65,   65,   65,   65,   78,
       78,   78,   89,   89,  119,  119,  135,  143,  135,  135,
      135,  138,  142,  138,  138,  138,  156,  156,  156,  156,
      156,  159,  159,  159,  159,  159,  123,  123,  123,  123,
      123,  183,  183,  187,  187,  187,  187,  187,  141,  134,
      133,  118,  196,  116,  196,  114,  112,   55,   54,  111,
      110,  109,  108,  107,  106,  105,  100,   99,   98,   97,
       96,   95,   94,   93,   86,   70,   69,   64,   63,   57,
       56,   55,   54,  196,    3,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,

      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196
    } ;

static const flex_int16_t yy_chk[649] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    9,   13,   90,    9,   19,   19,   21,
      208,   13,   20,   20,   20,   20,   58,   21,   23,   58,
       23,   23,   23,   23,   26,   26,   28,   28,  195,   31,
       65,   42,   23,   31,   91,   42,  114,   65,   90,    9,

       13,   22,  100,   22,   22,   22,   22,   23,   43,  100,
      121,  121,   58,   43,   22,   22,  193,   43,  192,   22,
      116,   22,  189,   91,  135,   31,   65,   22,  161,  114,
       22,   73,   73,   73,   73,  161,  182,   22,   42,   76,
       76,   76,   76,   73,   77,   77,   77,   77,  117,  116,
      117,   76,  181,  117,  117,  117,  117,  135,   73,  124,
      124,  124,  124,  128,  128,  128,   76,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,

       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   81,   81,   81,   81,   81,   81,   81,

       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,

       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,  125,
      125,  125,  125,  131,  131,  131,  131,  138,  156,  159,
      178,  187,  177,  131,  131,  131,  131,  162,  162,  162,
      162,  163,  163,  163,  163,  191,  131,  131,  131,  131,
      131,  131,  164,  164,  164,  164,  138,  188,  159,  178,
      187,  156,  176,  175,  188,  173,  169,  168,  165,  160,
      158,  157,  155,  153,  191,  152,  149,  148,  146,  145,
      143,  142,  141,  112,  110,  109,  108,  107,  105,  101,
       99,   98,   97,  188,  197,  197,  197,  197,  197,  198,

       96,  198,  198,  198,  199,  199,  199,  199,  199,  200,
      200,  200,  201,  201,  202,  202,  203,   94,  203,  203,
      203,  204,   93,  204,  204,  204,  205,  205,  205,  205,
      205,  206,  206,  206,  206,  206,  207,  207,  207,  207,
      207,  209,  209,  210,  210,  210,  210,  210,   92,   88,
       84,   74,   68,   67,   61,   60,   56,   55,   54,   51,
       49,   48,   47,   46,   45,   44,   41,   40,   39,   38,
       37,   36,   33,   32,   27,   17,   16,   12,   11,    8,
        7,    6,    5,    3,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,

      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[83] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "triton.l"
#line 2 "triton.l"
/*
 * ═══════════════════════════════════════════════════════════════════════════
 * TRITON LEXER - LEXICAL ANALYZER FOR TRITON DSL
 *
 * Descripción:
 *   Analizador léxico robusto para un lenguaje similar a Python con soporte
 *   para características especiales de Triton (lenguaje para kernels GPU).
 *
 * Arquitectura:
 *   - Manejo de indentación significativa (style Python)
 *   - Generación automática de INDENT/DEDENT tokens
 *   - Tabla de símbolos (hash map) para identificadores y literales
 *   - Output en lista doblemente enlazada para consumo por parser
 *
 * Compilación:
 *   $ flex triton.l
 *   $ gcc -o triton_lexer lex.yy.c -lfl -Wall -Werror
 *
 * Ejecución:
 *   $ ./triton_lexer codigo.py
 *
 * Autor: Generado + Mejorado
 * Fecha: 2026-04-27
 * ═══════════════════════════════════════════════════════════════════════════
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ═══════════════════════════════════════════════════════════════════════════
// CONFIGURACIÓN DEL LEXER
// ═══════════════════════════════════════════════════════════════════════════

#define HASH_SIZE 256
#define MAX_DEPTH 100
#define STRING_BUFFER_SIZE 1024

// ═══════════════════════════════════════════════════════════════════════════
// ESTADÍSTICAS DEL ANÁLISIS LÉXICO
// ═══════════════════════════════════════════════════════════════════════════

typedef struct {
    int total_tokens;
    int total_lines;
    int total_identifiers;
    int total_numeric_literals;
    int total_string_literals;
    int error_count;
} LexerStats;

LexerStats stats = {0};

// ═══════════════════════════════════════════════════════════════════════════
// ESTRUCTURA 1: HASH MAPS (Tabla de Símbolos y Literales)
// ═══════════════════════════════════════════════════════════════════════════

typedef struct HashNode {
    char* value;
    struct HashNode* next;
} HashNode;

HashNode* idTable[HASH_SIZE] = {NULL};
HashNode* literalTable[HASH_SIZE] = {NULL};

unsigned int hash(const char* str) {
    unsigned long hash_val = 5381;
    int c;
    while ((c = *str++)) {
        hash_val = ((hash_val << 5) + hash_val) + c;
    }
    return hash_val % HASH_SIZE;
}

void insert_into_table(HashNode** table, const char* value) {
    unsigned int index = hash(value);
    HashNode* curr = table[index];

    while(curr != NULL) {
        if(strcmp(curr->value, value) == 0) return;
        curr = curr->next;
    }

    HashNode* new_node = (HashNode*)malloc(sizeof(HashNode));
    if (!new_node) {
        fprintf(stderr, "[ERROR] No hay memoria para HashNode. Abortando.\n");
        exit(EXIT_FAILURE);
    }

    new_node->value = strdup(value);
    if (!new_node->value) {
        fprintf(stderr, "[ERROR] No hay memoria para strdup('%s'). Abortando.\n", value);
        free(new_node);
        exit(EXIT_FAILURE);
    }

    new_node->next = table[index];
    table[index] = new_node;
}

void print_table(HashNode** table, const char* title) {
    printf("\n--- %s ---\n", title);
    int empty = 1;

    for(int i = 0; i < HASH_SIZE; i++) {
        HashNode* curr = table[i];
        while(curr != NULL) {
            empty = 0;
            printf("%s\n", curr->value);
            curr = curr->next;
        }
    }

    if (empty) {
        printf("La tabla está vacía.\n");
    }
}

void free_hash_table(HashNode** table) {
    for (int i = 0; i < HASH_SIZE; i++) {
        HashNode* curr = table[i];
        while (curr != NULL) {
            HashNode* next = curr->next;
            free(curr->value);
            free(curr);
            curr = next;
        }
        table[i] = NULL;
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// ESTRUCTURA 2: PILA DE INDENTACIÓN
// ═══════════════════════════════════════════════════════════════════════════

int indent_stack[MAX_DEPTH] = {0};
int top = 0;

// ═══════════════════════════════════════════════════════════════════════════
// ESTRUCTURA 3: SCANNER OUTPUT (Double Linked List)
// ═══════════════════════════════════════════════════════════════════════════

typedef struct TokenNode {
    char* token_name;
    char* lexeme;
    size_t lexeme_len;
    int line_num;
    struct TokenNode* prev;
    struct TokenNode* next;
} TokenNode;

TokenNode* scanner_head = NULL;
TokenNode* scanner_tail = NULL;

void add_token(const char* token_name, const char* lexeme) {
    TokenNode* new_node = (TokenNode*)malloc(sizeof(TokenNode));
    if (!new_node) {
        fprintf(stderr, "[ERROR] No hay memoria para TokenNode. Abortando.\n");
        exit(EXIT_FAILURE);
    }

    new_node->token_name = strdup(token_name);
    if (!new_node->token_name) {
        fprintf(stderr, "[ERROR] No hay memoria para token_name. Abortando.\n");
        free(new_node);
        exit(EXIT_FAILURE);
    }

    new_node->lexeme = strdup(lexeme);
    if (!new_node->lexeme) {
        fprintf(stderr, "[ERROR] No hay memoria para lexeme. Abortando.\n");
        free(new_node->token_name);
        free(new_node);
        exit(EXIT_FAILURE);
    }

    new_node->lexeme_len = strlen(lexeme);
    new_node->line_num = yylineno;
    new_node->prev = scanner_tail;
    new_node->next = NULL;

    if (scanner_tail != NULL) {
        scanner_tail->next = new_node;
    } else {
        scanner_head = new_node;
    }
    scanner_tail = new_node;

    stats.total_tokens++;
    if (strcmp(token_name, "IDENTIFIER") == 0) stats.total_identifiers++;
    if (strcmp(token_name, "INT_LITERAL") == 0 ||
        strcmp(token_name, "FLOAT_LITERAL") == 0) stats.total_numeric_literals++;
    if (strcmp(token_name, "STRING_LITERAL") == 0) stats.total_string_literals++;
}

void print_scanner_output() {
    TokenNode* curr = scanner_head;
    while (curr != NULL) {
        if (curr->lexeme_len > 0) {
            printf("<%s,%s>\n", curr->token_name, curr->lexeme);
        } else {
            printf("<%s>\n", curr->token_name);
        }
        curr = curr->next;
    }
}

void free_scanner_output() {
    TokenNode* curr = scanner_head;
    while (curr != NULL) {
        TokenNode* next = curr->next;
        free(curr->token_name);
        free(curr->lexeme);
        free(curr);
        curr = next;
    }
    scanner_head = NULL;
    scanner_tail = NULL;
}

void print_statistics() {
    printf("\n════════════════════════════════════════════════════════════\n");
    printf("ESTADÍSTICAS DEL LEXER\n");
    printf("════════════════════════════════════════════════════════════\n");
    printf("Total de tokens:              %d\n", stats.total_tokens);
    printf("Identificadores únicos:       %d\n", stats.total_identifiers);
    printf("Literales numéricos únicos:   %d\n", stats.total_numeric_literals);
    printf("Literales de texto únicos:    %d\n", stats.total_string_literals);
    printf("Errores léxicos:              %d\n", stats.error_count);
    printf("════════════════════════════════════════════════════════════\n\n");
}

#line 913 "lex.yy.c"
#define YY_NO_INPUT 1
#line 915 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 244 "triton.l"


#line 247 "triton.l"
    /* ===================================================================
       1) ESPACIOS EN BLANCO Y CONTROL DE INDENTACIÓN
       =================================================================== */

#line 1138 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 197 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 585 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 251 "triton.l"
{ /* Ignorar espacios en medio de la línea */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 253 "triton.l"
{
    add_token("NEWLINE", "");

    int current_indent = 0;
    for(int i = 0; yytext[i] != '\0'; i++) {
        if(yytext[i] == ' ') {
            current_indent++;
        } else if(yytext[i] == '\t') {
            current_indent = (current_indent + 8) & ~7;
        }
    }

    if (current_indent > indent_stack[top]) {
        if (top < MAX_DEPTH - 1) {
            indent_stack[++top] = current_indent;
            add_token("INDENT", "");
        } else {
            fprintf(stderr,
                "[ERROR LEXICO FATAL] Nivel de indentación máximo superado\n"
                "  Máximo permitido: %d niveles\n"
                "  Línea: %d\n",
                MAX_DEPTH, yylineno);
            exit(EXIT_FAILURE);
        }
    } else if (current_indent < indent_stack[top]) {
        while (top > 0 && indent_stack[top] > current_indent) {
            top--;
            add_token("DEDENT", "");
        }
        if (indent_stack[top] != current_indent) {
            fprintf(stderr,
                "\n[ERROR LEXICO FATAL] Indentación inconsistente\n"
                "  Línea: %d\n"
                "  Indentación esperada: %d espacios\n"
                "  Indentación encontrada: %d espacios\n",
                yylineno, indent_stack[top], current_indent);
            exit(EXIT_FAILURE);
        }
    }
}
	YY_BREAK
/* ===================================================================
       2) COMENTARIOS
       =================================================================== */
case 3:
YY_RULE_SETUP
#line 298 "triton.l"
{ add_token("COMMENT", yytext); }
	YY_BREAK
/* ===================================================================
       3) PALABRAS RESERVADAS
       =================================================================== */
case 4:
YY_RULE_SETUP
#line 304 "triton.l"
{ add_token("KW_DEF", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 305 "triton.l"
{ add_token("KW_IF", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 306 "triton.l"
{ add_token("KW_ELIF", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 307 "triton.l"
{ add_token("KW_ELSE", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 308 "triton.l"
{ add_token("KW_FOR", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 309 "triton.l"
{ add_token("KW_WHILE", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 310 "triton.l"
{ add_token("KW_IN", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 311 "triton.l"
{ add_token("KW_BREAK", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 312 "triton.l"
{ add_token("KW_CONTINUE", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 313 "triton.l"
{ add_token("KW_RETURN", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 314 "triton.l"
{ add_token("KW_PASS", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 315 "triton.l"
{ add_token("KW_AND", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 316 "triton.l"
{ add_token("KW_OR", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 317 "triton.l"
{ add_token("KW_NOT", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 318 "triton.l"
{ add_token("KW_IS", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 319 "triton.l"
{ add_token("KW_TRUE", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 320 "triton.l"
{ add_token("KW_FALSE", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 321 "triton.l"
{ add_token("KW_NONE", yytext); }
	YY_BREAK
/* ===================================================================
       4) TOKENS TRITON ESPECÍFICOS
       =================================================================== */
case 22:
YY_RULE_SETUP
#line 327 "triton.l"
{ add_token("TL_IDENTIFIER", yytext); }
	YY_BREAK
/* ===================================================================
       5) IDENTIFICADORES
       =================================================================== */
case 23:
YY_RULE_SETUP
#line 333 "triton.l"
{
    add_token("IDENTIFIER", yytext);
    insert_into_table(idTable, yytext);
}
	YY_BREAK
/* ===================================================================
       6) TOKENS INVÁLIDOS: dígito seguido de letra (ej: 1a, 3xyz)
       Debe ir ANTES de INT_LITERAL e IDENTIFIER para que el maximal
       munch capture el token completo como error y no lo divida.
       =================================================================== */
case 24:
YY_RULE_SETUP
#line 344 "triton.l"
{
    fprintf(stderr,
        "[ERROR LEXICO] Token inválido '%s' - los identificadores no pueden comenzar con dígito\n"
        "  Línea: %d\n",
        yytext, yylineno);
    stats.error_count++;
}
	YY_BREAK
/* ===================================================================
       7) LITERALES NUMÉRICOS

       ORDEN IMPORTANTE:
         1. Prefijos inválidos (0x, 0b, 0o sin dígitos)  → error
         2. Exponente incompleto (1e, 1e+)               → error
         3. Enteros y floats válidos
       =================================================================== */
/* Prefijos numéricos sin dígitos después: usa trailing context (/) para
       no consumir el carácter siguiente y que sea analizado normalmente */
case 25:
/* rule 25 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 2);
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 363 "triton.l"
{
    fprintf(stderr,
        "[ERROR LEXICO] Prefijo hexadecimal sin valor '%s' - falta al menos un dígito hex\n"
        "  Línea: %d\n"
        "  Ejemplo válido: 0xFF, 0x1A3\n",
        yytext, yylineno);
    stats.error_count++;
}
	YY_BREAK
case 26:
/* rule 26 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 2);
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 372 "triton.l"
{
    fprintf(stderr,
        "[ERROR LEXICO] Prefijo binario sin valor '%s' - falta al menos un dígito binario\n"
        "  Línea: %d\n"
        "  Ejemplo válido: 0b1010, 0b11001\n",
        yytext, yylineno);
    stats.error_count++;
}
	YY_BREAK
case 27:
/* rule 27 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 2);
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 381 "triton.l"
{
    fprintf(stderr,
        "[ERROR LEXICO] Prefijo octal sin valor '%s' - falta al menos un dígito octal\n"
        "  Línea: %d\n"
        "  Ejemplo válido: 0o755, 0o17\n",
        yytext, yylineno);
    stats.error_count++;
}
	YY_BREAK
/* Exponente de float incompleto: 1e, 1e+, 1.5e- sin dígitos después */
case 28:
/* rule 28 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 391 "triton.l"
{
    fprintf(stderr,
        "[ERROR LEXICO] Exponente de float incompleto '%s' - falta el valor del exponente\n"
        "  Línea: %d\n"
        "  Ejemplo válido: 1e10, 1.5e-3, 2.0E+8\n",
        yytext, yylineno);
    stats.error_count++;
}
	YY_BREAK
/* Enteros válidos: hex, binario, octal, decimal */
case 29:
YY_RULE_SETUP
#line 401 "triton.l"
{
    add_token("INT_LITERAL", yytext);
    insert_into_table(literalTable, yytext);
}
	YY_BREAK
/* Floats válidos */
case 30:
YY_RULE_SETUP
#line 407 "triton.l"
{
    add_token("FLOAT_LITERAL", yytext);
    insert_into_table(literalTable, yytext);
}
	YY_BREAK
/* ===================================================================
       8) LITERALES DE TEXTO (Strings)

       ORDEN IMPORTANTE:
         1. Triple-quoted (antes que simples, son más largas)
         2. f-strings (antes que simples)
         3. Strings simples válidas
         4. Strings sin cerrar → error
       =================================================================== */
/* Triple-quoted: """..."""  y  '''...'''  (pueden ser multilinea) */
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 423 "triton.l"
{ add_token("STRING_LITERAL", yytext); }
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 424 "triton.l"
{ add_token("STRING_LITERAL", yytext); }
	YY_BREAK
/* f-strings: f"..."  y  f'...' */
case 33:
YY_RULE_SETUP
#line 427 "triton.l"
{ add_token("STRING_LITERAL", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 428 "triton.l"
{ add_token("STRING_LITERAL", yytext); }
	YY_BREAK
/* Strings simples válidas */
case 35:
YY_RULE_SETUP
#line 431 "triton.l"
{ add_token("STRING_LITERAL", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 432 "triton.l"
{ add_token("STRING_LITERAL", yytext); }
	YY_BREAK
/* Strings sin cerrar: llegan al fin de línea sin comilla de cierre */
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 435 "triton.l"
{
    fprintf(stderr,
        "[ERROR LEXICO] String sin cerrar (comilla doble)\n"
        "  Línea: %d\n"
        "  Sugerencia: agrega '\"' al final de la cadena\n",
        yylineno - 1);
    stats.error_count++;
}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 443 "triton.l"
{
    fprintf(stderr,
        "[ERROR LEXICO] String sin cerrar (comilla simple)\n"
        "  Línea: %d\n"
        "  Sugerencia: agrega \"'\" al final de la cadena\n",
        yylineno - 1);
    stats.error_count++;
}
	YY_BREAK
/* ===================================================================
       9) OPERADORES COMPUESTOS (deben ir ANTES que los simples)
       =================================================================== */
case 39:
YY_RULE_SETUP
#line 456 "triton.l"
{ add_token("OP_PLUS_ASSIGN", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 457 "triton.l"
{ add_token("OP_MINUS_ASSIGN", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 458 "triton.l"
{ add_token("OP_STAR_ASSIGN", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 459 "triton.l"
{ add_token("OP_SLASH_ASSIGN", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 460 "triton.l"
{ add_token("OP_DOUBLE_SLASH_ASSIGN", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 461 "triton.l"
{ add_token("OP_MOD_ASSIGN", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 462 "triton.l"
{ add_token("OP_BIT_AND_ASSIGN", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 463 "triton.l"
{ add_token("OP_BIT_OR_ASSIGN", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 464 "triton.l"
{ add_token("OP_BIT_XOR_ASSIGN", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 465 "triton.l"
{ add_token("OP_LSHIFT_ASSIGN", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 466 "triton.l"
{ add_token("OP_RSHIFT_ASSIGN", yytext); }
	YY_BREAK
/* ===================================================================
       10) OPERADOR DE ASIGNACIÓN SIMPLE
       =================================================================== */
case 50:
YY_RULE_SETUP
#line 472 "triton.l"
{ add_token("OP_ASSIGN", yytext); }
	YY_BREAK
/* ===================================================================
       10) OPERADORES ARITMÉTICOS
       =================================================================== */
case 51:
YY_RULE_SETUP
#line 478 "triton.l"
{ add_token("OP_DOUBLE_SLASH", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 479 "triton.l"
{ add_token("OP_PLUS", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 480 "triton.l"
{ add_token("OP_MINUS", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 481 "triton.l"
{ add_token("OP_STAR", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 482 "triton.l"
{ add_token("OP_SLASH", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 483 "triton.l"
{ add_token("OP_MOD", yytext); }
	YY_BREAK
/* ===================================================================
       11) OPERADORES RELACIONALES
       =================================================================== */
case 57:
YY_RULE_SETUP
#line 489 "triton.l"
{ add_token("OP_LE", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 490 "triton.l"
{ add_token("OP_GE", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 491 "triton.l"
{ add_token("OP_EQ", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 492 "triton.l"
{ add_token("OP_NEQ", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 493 "triton.l"
{ add_token("OP_LT", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 494 "triton.l"
{ add_token("OP_GT", yytext); }
	YY_BREAK
/* ===================================================================
       12) OPERADORES BIT A BIT
       =================================================================== */
case 63:
YY_RULE_SETUP
#line 500 "triton.l"
{ add_token("OP_LSHIFT", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 501 "triton.l"
{ add_token("OP_RSHIFT", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 502 "triton.l"
{ add_token("OP_BIT_AND", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 503 "triton.l"
{ add_token("OP_BIT_OR", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 504 "triton.l"
{ add_token("OP_BIT_XOR", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 505 "triton.l"
{ add_token("OP_BIT_NOT", yytext); }
	YY_BREAK
/* ===================================================================
       13) DELIMITADORES Y PUNTUACIÓN
       =================================================================== */
case 69:
YY_RULE_SETUP
#line 511 "triton.l"
{ add_token("ARROW", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 512 "triton.l"
{ add_token("LPAREN", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 513 "triton.l"
{ add_token("RPAREN", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 514 "triton.l"
{ add_token("LBRACKET", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 515 "triton.l"
{ add_token("RBRACKET", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 516 "triton.l"
{ add_token("LBRACE", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 517 "triton.l"
{ add_token("RBRACE", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 518 "triton.l"
{ add_token("COMMA", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 519 "triton.l"
{ add_token("COLON", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 520 "triton.l"
{ add_token("DOT", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 521 "triton.l"
{ add_token("SEMICOLON", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 522 "triton.l"
{ add_token("AT", yytext); }
	YY_BREAK
/* ===================================================================
       14) FIN DE ARCHIVO
       =================================================================== */
case YY_STATE_EOF(INITIAL):
#line 528 "triton.l"
{
                    while(top > 0) {
                        add_token("DEDENT", "");
                        top--;
                    }

                    print_scanner_output();
                    print_table(idTable, "TABLA DE IDENTIFICADORES");
                    print_table(literalTable, "TABLA DE LITERALES NUMERICOS");
                    print_statistics();

                    return 0;
                }
	YY_BREAK
/* ===================================================================
       ERROR LÉXICO
       =================================================================== */
case 81:
YY_RULE_SETUP
#line 546 "triton.l"
{
    fprintf(stderr,
        "[ERROR LEXICO] Carácter inesperado '%s'\n"
        "  Línea: %d\n"
        "  Carácter ASCII: %d (0x%X)\n",
        yytext, yylineno, (unsigned char)yytext[0], (unsigned char)yytext[0]);
    stats.error_count++;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 555 "triton.l"
ECHO;
	YY_BREAK
#line 1826 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 197 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 197 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 196);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 555 "triton.l"


int yywrap() { return 1; }

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "Uso: %s <archivo_de_entrada.py>\n", argv[0]);
        return EXIT_FAILURE;
    }

    FILE *archivo = fopen(argv[1], "r");
    if (!archivo) {
        fprintf(stderr, "Error: No se pudo abrir el archivo '%s'\n", argv[1]);
        perror("fopen");
        return EXIT_FAILURE;
    }

    yyin = archivo;
    int result = yylex();

    fclose(archivo);
    free_scanner_output();
    free_hash_table(idTable);
    free_hash_table(literalTable);

    return result;
}
